# Read-only: where do the XUnity dictionary keys live — as C# string literals or elsewhere (scene/bundle data)?
import os, re
ROOT = os.path.dirname(os.path.abspath(__file__))
DICT = r"D:\Games\Svarog's Dream\AutoTranslator\Translation\ru\Text\_AutoGeneratedTranslations.txt"
src = []
for dp, dn, fn in os.walk(os.path.join(ROOT, "acs")):
    for f in fn:
        if f.endswith(".cs"):
            src.append(open(os.path.join(dp, f), encoding="utf-8", errors="replace").read())
literals = set()
lit_re = re.compile(r'"((?:[^"\\]|\\.)*)"')
for s in src:
    for m in lit_re.finditer(s):
        literals.add(m.group(1).replace('\\"', '"').replace("\\n", "\n"))
blob = "\n".join(literals)
keys = []
for line in open(DICT, encoding="utf-8-sig"):
    line = line.rstrip("\n")
    if "=" not in line or line.startswith("//"):
        continue
    k = line.split("=", 1)[0].replace("\\n", "\n")
    keys.append(k)
exact = sum(1 for k in keys if k in literals)
part = sum(1 for k in keys if k not in literals and len(k) > 6 and k in blob)
print("dictionary keys:", len(keys))
print("C# string literals in Assembly-CSharp:", len(literals))
print("keys equal to a C# literal:", exact)
print("keys found inside a longer C# literal:", part)
print("keys not in code (scene/prefab/bundle text or composed at runtime):", len(keys) - exact - part)
